### ISSUE TITLE
Forked VM failed with exit code 134

### ISSUE THREAD

**Issue by stsypanov** [jvm-profiling-tools/async-profiler#180]
Hi,

I've run into VM crash when profilin JMH benchmark.

```java
Iteration  11: #
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc98b469494, pid=18575, tid=18576
#
# JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x1c494]  StackFrame::pop(bool)+0x84
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/sergei/dev/benchmarks/hs_err_pid18575.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
<forked VM failed with exit code 134>
<stdout last='20 lines'>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc98b469494, pid=18575, tid=18576
#
# JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x1c494]  StackFrame::pop(bool)+0x84
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/sergei/dev/benchmarks/hs_err_pid18575.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
</stdout>
<stderr last='20 lines'>
</stderr>

Benchmark had encountered error, and fail on error was requested
Exception in thread "main" org.openjdk.jmh.runner.RunnerException: Benchmark caught the exception
	at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:578)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:320)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
	at com.luxoft.logeek.benchmark.BenchmarkRunner.main(BenchmarkRunner.java:46)
Caused by: org.openjdk.jmh.runner.BenchmarkException: Benchmark error
	at org.openjdk.jmh.runner.Runner.doFork(Runner.java:771)
	at org.openjdk.jmh.runner.Runner.runSeparate(Runner.java:663)
	at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:561)
	... 3 more
	Suppressed: java.lang.IllegalStateException: Forked VM failed with exit code 134
		... 6 more
```

How to reproduce

1. Run this [benchmark](https://github.com/stsypanov/benchmarks/blob/master/benchmark-runners/src/main/java/com/luxoft/logeek/benchmark/concurrency/ConcurrentReferenceHashMapInstantiation.java) on openjdk-11 under Linux
```java
@State(Scope.Thread)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Fork(jvmArgsAppend = {"-XX:+UseParallelGC", "-Xms2g", "-Xmx2g"})
public class ConcurrentReferenceHashMapInstantiation {

  @Benchmark
  public Object constructor() {
    return new org.springframework.util.ConcurrentReferenceHashMap<>();
  }
}
```
2. Try to profile it using `./profiler.sh -d 180 -i 10 -o flat=50 -f ~/dev/async-profiler/log.txt pid`
3. VM craches.

Here's the `hs_err_pid18575.log`: [https://yadi.sk/d/gv-C7ywMiMj2rQ](https://yadi.sk/d/gv-C7ywMiMj2rQ)

**Comment by apangin** [comment]
Thank you for the report!
It was an interesting bug. The profiler crashed when the sampled PC occured at the very first byte of the mapped `classes.jsa` archive - it really happened to be an executable instruction, but the attempt to read a byte at PC-1 caused segmentation fault.

I committed the fixed. Please check if it helps.

**Comment by stsypanov** [comment]
It's very cool to have this issue fixed in a day. Thanks, it works!
