### ISSUE TITLE
Tomcat exception when using wall profiler

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#295]
When testing async-profiler in `wall` mode in a `tomcat:9-jre11-slim` docker container, I noticed lots of these exceptions:

```
24-Jan-2020 15:21:08.911 WARNING [main] org.apache.catalina.core.StandardServer.await The socket listening for the shutdown command experienced an unexpected timeout [208] milliseconds after the call to accept(). Is this an instance of bug 56684?
java.net.SocketTimeoutException: Accept timed out
at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:459)
at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:551)
at java.base/java.net.ServerSocket.accept(ServerSocket.java:519)
at org.apache.catalina.core.StandardServer.await(StandardServer.java:478)
at org.apache.catalina.startup.Catalina.await(Catalina.java:783)
at org.apache.catalina.startup.Catalina.start(Catalina.java:729)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
```

They did not appear in `itimer` mode and the number of exception correlates with the sampling interval. Did you see this before? Any idea how to fix that?

**Comment by apangin** [comment]
This is a JDK bug. I've submitted the issue: https://bugs.openjdk.java.net/browse/JDK-8237858

In fact, the bug can be easily reproduced even without the profiler. Run the following program
```
public class SocketAcceptTest {
    public static void main(String[] args) throws Exception {
        new ServerSocket(0).accept();
    }
}
```
then find `tid` of the main thread, and call
```
kill -SIGPIPE tid
```
The program will fail with the same exception.

In wall-clock mode, async-profiler sends signals to all threads in order to obtain their stack traces. The signal interrupts the syscall with `EINTR`, and JDK should restart the syscall, but it does not.

The problem does not happen on JDK 8 and on JDK 13.

**Comment by felixbarny** [comment]
Thanks Andrei! It also does not seem to affect Tomcat too much, other than constantly printing the exception.

**Comment by apangin** [comment]
I thought I could workaround this issue in the profiler.

Now, when async-profiler detects an interrupted `poll()` syscall, it forces the restart by patching the instruction pointer. Please check if the fix helps.

**Comment by felixbarny** [comment]
I can confirm that with 1.7-ea the exceptions are gone now. Thanks!
