### ISSUE TITLE
Attaching profiler in method mode (profiling classloader) to running JVM may crash method execution

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#340]
Java version
```
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Corretto-11.0.4.11.1 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.4.11.1 (build 11.0.4+11-LTS, mixed mode)
```

Sample program that can crash:
```java
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

class Classes {
    public static void main(String[] args) throws Exception {
        long j = 0;
        List<ClassLoader> classLoaders = new ArrayList<>();
        for (int i = 0; i < 100_000; i++) {
            if ((i + 1) % 1000 == 0) {
                System.out.println(i + 1);
            }
            String fictiousClassloaderJAR = "file:" + j++ + ".jar";
            URL[] fictiousClassloaderURL = new URL[]{new URL(fictiousClassloaderJAR)};
            URLClassLoader newClassLoader = new URLClassLoader(fictiousClassloaderURL);
            classLoaders.add(newClassLoader);

            ClassToOptimize classToOptimize = (ClassToOptimize) Proxy.newProxyInstance(newClassLoader,
                    new Class<?>[]{ClassToOptimize.class},
                    new ClassToOptimizeInvocationHandler(new ClassToOptimizeImpl()));
        }
        Scanner scan = new Scanner(System.in);
        scan.nextLine();
    }

    public interface ClassToOptimize {
        void run();
    }

    static public class ClassToOptimizeImpl implements ClassToOptimize {
        public void run() {
            for (int i = 0; i < 1000; i++) {
                new Object();
                doSomething(1 + (i % 10));
            }
        }

        private void doSomething(int o) {
            int acc = 0;
            for (int i = 0; i < o; i++) {
                acc = add(acc, i);
            }
        }

        private int add(int acc, int i) {
            return acc + sqrt(i);
        }

        private int sqrt(int i) {
            return (int) Math.sqrt(i);
        }
    }

    public static class ClassToOptimizeInvocationHandler implements InvocationHandler {
        private Object impl;

        public ClassToOptimizeInvocationHandler(Object impl) {
            this.impl = impl;
        }

        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            if (Object.class == method.getDeclaringClass()) {
                String name = method.getName();
                if ("equals".equals(name)) {
                    return proxy == args[0];
                } else if ("hashCode".equals(name)) {
                    return System.identityHashCode(proxy);
                } else if ("toString".equals(name)) {
                    return proxy.getClass().getName() + "@" +
                            Integer.toHexString(System.identityHashCode(proxy)) +
                            ", with InvocationHandler " + this;
                } else {
                    throw new IllegalStateException(String.valueOf(method));
                }
            }

            return method.invoke(impl, args);
        }
    }
}
```

Run program with
```
java Classes
```

As soon as JVM starts run profiler with
```
./profiler.sh -d 10 -e java.lang.ClassLoader.loadClass `pgrep -f Classes`
```

It looks like some race condition, but sometimes I got an exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void one.profiler.Instrument.recordSample()'
	at one.profiler.Instrument.recordSample(Native Method)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:651)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:413)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
	at Classes.main(Classes.java:23)
```

Profiling as java agent works fine.

**Comment by apangin** [comment]
I committed the fix

**Comment by krzysztofslusarski** [comment]
Great, it works now. Thank you.
