### ISSUE TITLE
Profiler causes IOException when using Windows CIFS share

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#384]
A user of the Elastic APM Java agent reported that when using async-profiler, they get an exception when closing `FileOutputStream`s that correspond to a file on a Windows CIFS share that's mounted into a Linux server.

The exception they get is 

```
java.io.IOException: Input/output error
	at java.io.FileOutputStream.close0(Native Method)
	at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
	at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
	at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
	at java.io.FileOutputStream.close(FileOutputStream.java:354)
```

More info on this thread: https://discuss.elastic.co/t/profiling-inferred-spans-enabled-causes-ioexception-input-output-error-when-closing-a-filestream-on-a-nas-server-that-uses-windows/254911

> Disabling `profiling_inferred_spans seems` to fix the issue because then the async-profiler is not being used anymore.

**Comment by apangin** [comment]
Interesting. I guess this may be similar to #295.

Normally, `close` syscall is an atomic operation with respect to userland code. However, on a network filesystem `close` may result in underlying network I/O which in turn can be interrupted by a [profiling] signal.

If this is the case, then this is a JDK bug. As far as I see from the JDK source code, it does not restart `close` when it returns `EINTR`, even though [man page](https://man7.org/linux/man-pages/man2/close.2.html) lists `EINTR` as a possible outcome of `close`.

**Comment by apangin** [comment]
I could reproduce the problem. In my case, the exception message is different though:
```
Exception in thread "main" java.io.IOException: Interrupted system call
        at java.io.FileOutputStream.close0(Native Method)
        at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
        at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
        at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
        at java.io.FileOutputStream.close(FileOutputStream.java:354)
        at CifsBug.main(CifsBug.java:15)
```

I've submitted the corresponding OpenJDK issue: https://bugs.openjdk.java.net/browse/JDK-8259943

I'll see if it's possible to create a workaround in async-profiler.

Another possible workaround is to replace `FileOutputStream` with `FileChannel`, which does not suffer from the mentioned issue.

**Comment by apangin** [comment]
I created a workaround the same way like in #295:
if profiler detects that `close` was interrupted by a signal, it substitures the return code to indicate success, because JDK is not prepared to handle EINTR result.

Here is a special build with the fix: [async-profiler-1.8.3-eintr-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/5832503/async-profiler-1.8.3-eintr-linux-x64.tar.gz)

**Comment by NickWemekamp** [comment]
Hi,

I've tested the snapshot APM release with the new version of the async profiler unfortunately I still get the same IOException:
`Caused by: java.io.IOException: Input/output error
	at java.io.FileOutputStream.close0(Native Method)
	at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
	at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
	at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
	at java.io.FileOutputStream.close(FileOutputStream.java:354)`

Maybe it is JDK specific? Because my stack trace message is also different.
`java -version` produces the following result:
```
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b32)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b32, mixed mode)
```

This occured 3 out of 3 times when I copy a uploaded file of 100MB. If the file size is smaller it sometimes goes through successfully. I suspect this is because then the profiling_inferred_spans_sampling_interval (from the APM agent) has not happened during the time the file copy took.

**Comment by apangin** [comment]
@NickWemekamp I'm sure this is not JDK specific, but rather specific to the version of Linux kernel. What version do you have?

I tried 3.10, 4.16 and 5.3.  
On 5.3 I got `EINTR` ("Interrupted system call"), while on older kernels I saw `EIO` ("Input/output error").  
I guess, a change in the error code is a result of [this kernel patch](https://lore.kernel.org/patchwork/patch/903732/).

When I tried to workaround `EIO` the same way like `EINTR`, the exception disappeared, but the result file got broken. Furthermore, even when interrupted `close` is handled on 5.3 either in JDK or in async-profiler, the output sometimes appears broken, too. Seems like the actual bug is even deeper - in CIFS driver in the kernel. Unforunately, async-profiler can do nothing about it - I'll simply revert my workaround attempt back.

The good news is that the problems seems to be solvable by mounting options. After I disabled CIFS cache (`cache=none`), I don't see exceptions anymore. This may affect I/O performance though.

**Comment by NickWemekamp** [comment]
Thanks you for your answer! Turning the cifs cache off solves the issue for me too. Was definitely not expecting the original bug to be this low level :)

**Comment by apangin** [comment]
@NickWemekamp Thanks for the confirmation. I'm closing the issue then.
