### ISSUE TITLE
Some JVM processes return -1 on attach attempt

### ISSUE THREAD

**Issue by egor-ryashin** [jvm-profiling-tools/async-profiler#45]
I cannot attach to some JVM processes.
I made *profiler.sh* output more info:
```bash
    collect)
        $JATTACH $PID load $PROFILER true start,file=$FILE$INTERVAL$FRAMEBUF #> /dev/null
        if [ $? -ne 0 ]; then
            exit 1
        fi
```
Got this:
```
~/async-profiler $ sudo -u xncore ./profiler.sh -d 10 3515
Connected to remote JVM
Response code = -1
```
Is there a way to debug it further?

**Comment by apangin** [comment]
Is anything printed in target JVM's console?
Does `System.load("/path/to/libAsyncProfiler.so")` succeeds?

**Comment by apangin** [comment]
Response code -1 is printed by the agent. This means, `libAsyncProfiler.so` was successfully loaded and `Agent_OnAttach` was called. If `Agent_OnAttach` fails, it prints the error message to `stderr` of JVM process.

**Comment by egor-ryashin** [comment]
No messages in stderr/stdout.

**Comment by egor-ryashin** [comment]
I don't see 'Profiling started'.
A part of **strace** log:
```
access("/bin/sleep", X_OK)              = 0
stat("/bin/sleep", {st_mode=S_IFREG|0755, st_size=38984, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/bin/sleep", R_OK)              = 0
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ff0d14a89d0) = 17112
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {0x55beab3f2b10, [], SA_RESTORER, 0x7ff0d0a69fd0}, {SIG_DFL, [], SA_RESTORER, 0x7ff0d0a69fd0}, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 17112
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7ff0d0a69fd0}, {0x55beab3f2b10, [], SA_RESTORER, 0x7ff0d0a69fd0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=17112, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
wait4(-1, 0x7ffc3c948f00, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn()                          = 0
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ff0d14a89d0) = 17113
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {0x55beab3f2b10, [], SA_RESTORER, 0x7ff0d0a69fd0}, {SIG_DFL, [], SA_RESTORER, 0x7ff0d0a69fd0}, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 17113
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7ff0d0a69fd0}, {0x55beab3f2b10, [], SA_RESTORER, 0x7ff0d0a69fd0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=17113, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
wait4(-1, 0x7ffc3c949040, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn()                          = 0
read(255, "\nshow_agent_output\n", 2964) = 19
stat("/tmp/async-profiler.pytry3se", 0x7ffc3c949360) = -1 ENOENT (No such file or directory)
read(255, "", 2964)                     = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
Java version:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by apangin** [comment]
Does `grep asyncProfiler /proc/<javapid>/maps` show anything?

**Comment by egor-ryashin** [comment]
Started for 30 seconds, no _async_ in _maps_.

**Comment by apangin** [comment]
Try calling `System.load("/path/to/libAsyncProfiler.so")` - does the call succeed?

**Comment by egor-ryashin** [comment]
I guess this is it. 
```/usr/lib/jvm/java-8-oracle/jre/bin/java -cp . temp2 /home/egor.ryashin/async-profiler/build/libasyncProfiler.so 
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/egor.ryashin/async-profiler/build/libasyncProfiler.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/egor.ryashin/async-profiler/build/libasyncProfiler.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at temp2.main(temp2.java:3)
```
I don't have proper dynamic libs there.

**Comment by apangin** [comment]
OK. I think `profiler.sh` script needs to print some message when the library fails to load. Also a paragraph in troubleshooting section would be useful. I'll leave the issue open until this is fixed.

**Comment by apangin** [comment]
I've fixed `profiler.sh` to print diagnostic message in such cases.
