### ISSUE TITLE
StackMapTable error while profiling a kotlin class

### ISSUE THREAD

**Issue by yigit** [jvm-profiling-tools/async-profiler#531]
I'm getting the following error while trying to count the number of calls to a certain method during a kotlin compilation:

```
e: java.lang.ClassFormatError: StackMapTable format error: bad offset for Uninitialized in method 'org.jetbrains.kotlin.types.KotlinType com.google.devtools.ksp.processing.impl.ResolverImpl.toWildcard(org.jetbrains.kotlin.types.KotlinType, org.jetbrains.kotlin.load.kotlin.TypeMappingMode)'
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:153)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
```

Attached, you can find a sample gradle project that reproduces the problem. I tried but failed to reproduce it in a simpler setup.

To reproduce, execute:

```
./gradlew  gw kspKotlin  --no-daemon -Dkotlin.compiler.execution.strategy=in-process '-Dorg.gradle.jvmargs=-agentpath:<SO_PATH>=start,event=com.google.devtools.ksp.processing.impl.ResolverImpl.*'
```
Where SO_PATH is set to the path of the `libasyncProfiler.so` file.

If you are not familiar with gradle / kotlin; what this command does is:

* `kspKotlin`: execute the ksp task (see :  https://github.com/google/ksp)
* `--no-daemon`: dont use a gradle daemon
* `-Dkotlin.compiler.execution.strategy=in-process`: tells kotlin gradle plugin to not use its compilation daemon (so compilation happens in the same process as gradle)

I'm seeing this error on Mac OS Monterey (haven't tried on a linux machine yet)

```
➜  AsyncProfilerError git:(main) java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
async profiler build: `async-profiler-2.6-macos` 

Lmk if there is any additional information I can provide.

[AsyncProfilerError.zip](https://github.com/jvm-profiling-tools/async-profiler/files/7901648/AsyncProfilerError.zip)

**Comment by apangin** [comment]
Thank you for the detailed bug report with the test case.
I've committed the fix.
