### ISSUE TITLE
[jfr2flame] `Invalid string encoding` when converting to flame graph

### ISSUE THREAD

**Issue by sureshg** [jvm-profiling-tools/async-profiler#636]
The `jfr` file was created using [JDK 20 EA ](https://jdk.java.net/20/)build. I am not sure if it's really a supported version for async-profiler converter. The recording is working fine with tools like `VisualVM` and `JMC`

```bash
$ java -cp converter.jar jfr2flame openjdk-playground.jfr output.html
Exception in thread "main" java.lang.IllegalArgumentException: Invalid string encoding
	at one.jfr.JfrReader.getString(JfrReader.java:498)
	at one.jfr.JfrReader.readThreads(JfrReader.java:336)
	at one.jfr.JfrReader.readConstants(JfrReader.java:307)
	at one.jfr.JfrReader.readConstantPool(JfrReader.java:296)
	at one.jfr.JfrReader.readChunk(JfrReader.java:222)
	at one.jfr.JfrReader.<init>(JfrReader.java:82)
	at jfr2flame.main(jfr2flame.java:232)
```

[openjdk-playground.jfr.zip](https://github.com/jvm-profiling-tools/async-profiler/files/9334773/openjdk-playground.jfr.zip)

**Comment by apangin** [comment]
Thanks for reporting. The fix is committed.

**Comment by sureshg** [comment]
Sorry to comment on close thread. I am seeing the same issue on the latest openjdk 22 ea build? Should i create a new issue?
```
$ java -cp ~/install/tools/converter.jar jfr2flame test.jfr flame.html
Exception in thread "main" java.lang.IllegalArgumentException: Invalid string encoding
        at one.jfr.JfrReader.getString(JfrReader.java:515)
        at one.jfr.JfrReader.readActiveSetting(JfrReader.java:200)
        at one.jfr.JfrReader.readEvent(JfrReader.java:142)
        at jfr2flame.convert(jfr2flame.java:56)
        at jfr2flame.main(jfr2flame.java:258)

```

**Comment by apangin** [comment]
@sureshg Yes, please create a new issue and attach a problematic .jfr
